### ISSUE TITLE
Validations (B01-SRV)

### ISSUE THREAD

**Issue by ItsAnkan** [destryptor/MASK-W23-Sharanya-22CS10088#6]
This is an extra feature, which you may consider adding.

## Why

Since your form is taking specific data, like phone number, and Name, you can add some validations for the data.
Some examples of validations are -
- Checking if phone number is 10 digits long
- Name should contain only alphabets, no numbers or other things
- etc.

## How

Validation can be done client side (using regex inside the script tags) or in the server-side (also using js, and there are libraries, like [express-validator](https://express-validator.github.io/docs) for doing this). Each one comes with their own pros and cons.

**Comment by Goose-Of-War** [comment]
Looks like I gotta booli you into using MD properly 🥸

**Comment by destryptor** [comment]
Thank you for the suggestion Ankan. I learnt something new. I added a client side validation in the form.html file. I wanted to try server-side validation too, but load before midsems ;-;
For goos, I have rewritten the README.md file using only MD. Hope i won't get bullied now :)

**Comment by ItsAnkan** [comment]
Since midsems are over now, you can try to implement the server-side validation. Remember, you have till Oct 2, so thats like a week of free time you can experiment with 🙂

**Comment by destryptor** [comment]
Implemented server-side validation. It was a huge pain since it was my first time trying to implement it, and I don't think I have properly got the hang of it yet. I would still prefer client side verification for now XD since it seems more simplistic to me, but I understand why server side validation is necessary. Please check the code once and lemme know if I can improve upon it. Thanks
I am not closing this issue for now

**Comment by Goose-Of-War** [comment]
Heyo. Add some "not empty" validations for all fields and you are essentially good to go for closing this issue

**Comment by destryptor** [comment]
Added the not empty validations for all fields. Thanks :)
